### ISSUE TITLE
Evaluation training on higher resolutions

### ISSUE THREAD

**Issue by mokamp** [tinghuiz/SfMLearner#13]
How did you obtain the depth predictions on Make3D? Can the network be evaluated/trained on higher resolution inputs or do you need to scale the inputs accordingly?

**Comment by tinghuiz** [comment]
For Make3D I first resize the image to height=512 and width=384, and then crop the center 192 rows as the input to the network. The network is fully-convolutional, so can be applied to arbitrary resolutions. But due to the particular structures of KITTI/Cityscapes scenes, it might have learned a strong prior of the scene scale that might or might not work well for inputs of very different resolutions.

**Comment by mokamp** [comment]
Alright, thank you so much for clarifying!
