### ISSUE TITLE
About connect the 5-frames snippets into a complete sequence

### ISSUE THREAD

**Issue by royal-feng** [tinghuiz/SfMLearner#26]
I want to test the whole sequence pose estimate, but the pose net output the 5-frames snippets. By observing the 5-frames snippets(format: timestamp tx ty tz qx qy qz qw), the world coordinate system in each snippets is different ,how to change it to the same world coordinate system,such as reference frame is the NO.0 frame.And how to reduce the error while project to the same coordinate system.

**Comment by tinghuiz** [comment]
A naive way is to do pose estimation in a sliding window manner (i.e. [t0, t1, t2, t3, t4] and then [t4, t5, t6, t7, t8, t9] and so on), and then transform all poses to be w.r.t. the reference frame t0. Since there's overlap between consecutive snippets, it is straightforward to transform the poses back to t0 by tracing back recursively.
