### ISSUE TITLE
Generating the actual depth values of the kitti dataset

### ISSUE THREAD

**Issue by likui01** [tinghuiz/SfMLearner#9]
hi,
I tested your evaluation code it work fine with the prediction downloaded.
But im trying to find a prediction for a specific image from the kitti data set. 
in which format do you save the prediction of the disparity.
im more interested in the actual depth values of a single image.

**Comment by tinghuiz** [comment]
Hi, the predictions correspond to the test frames in the order of https://github.com/tinghuiz/SfMLearner/blob/master/data/kitti/test_files_eigen.txt. The depth predicted by our model has scale ambiguity, which is why there's a scale matching step in the evaluation (https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/eval_depth.py#L66-L67).

**Comment by likui01** [comment]
thank you for the response.
If i give an image similar to kitti dataset for testing. The values of the depth map predicted values are absolute distance. right? what actually the disparities represents, the one obtained  from 
_pred = sfm.inference(I[None,:,:,:], sess, mode=mode)_
or is there some manipulation involved.  I saw in kitti dataset you converted disparities to distance using camera parameters.

**Comment by tinghuiz** [comment]
`pred = sfm.inference(I[None,:,:,:], sess, mode=mode)` will give you per-pixel depth (but again up to a scaling factor).
