### ISSUE TITLE
error on the 'Namespace' object has no attribute 'dump_root'

### ISSUE THREAD

**Issue by lixiangyu-1008** [tinghuiz/SfMLearner#93]
thanks for the code.but when I run the prepare_train_data.py as 
python data/prepare_train_data.py --dataset_dir=/home/lli/tensorflow/SfMLearner/data/kitti/ --dataset_name='kitti_raw_eigen' --dump_root=/home/lli/tensorflow/SfMLearner/data/kitti/resulting/formatted/data/ --seq_length=3 --img_width=416 --img_height=128 --num_threads=4

it run the error 'Namespace' object has no attribute 'dump_root'

**Comment by tinghuiz** [comment]
That is weird... Is anyone else encountering the same error?

**Comment by lixiangyu-1008** [comment]
dump_dir = os.path.join(args.dump_root, example['folder_name'])  error happen in this code.

**Comment by lixiangyu-1008** [comment]
and then I use the real  folder path /home/lli/tensorflow/SfMLearner/data/kitti/resulting/formatted/data/ replace the  args.dump_root ,the code like this "dump_dir = os.path.join("/home/lli/tensorflow/SfMLearner/data/kitti/resulting/formatted/data/",example['folder_name'])" it worked, but I don't think this is a  good method.

**Comment by francois-baptiste** [comment]
I got the same error with  --num_threads=4
A way around is to set num_threads to 1.

**Comment by Huang-Jin** [comment]
I have ever encountered such problem and successfully dealt with it without setting num_threads to 1. But I'm very sorry, now I forget how to deal with this. At least, for me, I could run my code well with following command in my computer: 
```
--dataset_dir=/data/kitti/ --dataset_name='kitti_raw_eigen' --dump_root=/data/kitti/formatted/ --seq_length=3 --img_width=416 --img_height=128 --num_threads=4
```

So, I think the problem is not about the threads. I hope this could hep you.

**Comment by Huang-Jin** [comment]
Oh, I found the way to deal with it just now.
For some reason, the function dump_example couldn't get the global variable args.
So such errors encountered. I guess it is relative to the multi-threads.
The answer of @francois-baptiste will help because it only used one thread and the global variable is available.
For me, I dealt with it by changing the parameters of dump_example from
```
def dump_example(n):
``` 
to 
```
def dump_example(n, args):
``` 
and changed 
```
Parallel(n_jobs=args.num_threads)(delayed(dump_example)(n) for n in range(data_loader.num_train))
```
into

```
Parallel(n_jobs=args.num_threads)(delayed(dump_example)(n, args) for n in range(data_loader.num_train))
```

**Comment by lixiangyu-1008** [comment]
@Huang-Jin ,your answer deal with the issue,thanks a lot. Alao thanks to @tinghuiz @francois-baptiste

**Comment by tinghuiz** [comment]
@Huang-Jin Do you mind submitting a PR for the fix? Also, thanks for helping address some of the open issues! :)

**Comment by Huang-Jin** [comment]
What does it mean to submit a PR, I'm not very sure about it?

**Comment by tinghuiz** [comment]
Oh, I meant pull request.

**Comment by Huang-Jin** [comment]
Ok, I will do it tomorrow. Now I have to sleep. Good night! :)
